version: '3.3'

networks:
  bridge:
    driver: bridge

services:
  app:
    image: playsms/playsms
    networks:
      - bridge
    ports:
      - "80:8000"
      - "2222:22"
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: